# Generated by Django 3.1.3 on 2020-11-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_notebookproduct_smartphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotebookProduct',
            new_name='Notebook',
        ),
    ]
