# Generated by Django 3.1.3 on 2020-11-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
